export const SearchActions = {
  GET_AIRPORTS: 'GET_AIRPORTS',
  GET_AIRPORTS_REQUEST: 'GET_AIRPORTS_REQUEST',
  GET_AIRPORTS_SUCCESS: 'GET_AIRPORTS_SUCCESS',
  GET_AIRPORTS_FAILED: 'GET_AIRPORTS_FAILED',
  SET_PER_PAGE_COUNT: 'SET_PER_PAGE_COUNT',
};
